name: SuperVanish
main: erkam2002\Vanish
version: 3.0.0-B1
author: [VMPE Development Team]
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
commands:
  supervanish:
    description: "Vanish your self"
    aliases: [sv]
permissions:
  supervanish.spectate:
    description: "Vanish use perm"
    default: op
