--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ZPlayzMCPE/VoidMinerPE-plugins
branches:
- master
projects:
  AdminFun:
    path: AdminFun/
  AdvancedKits:
    path: AdvancedKits/
  AllAPILoader-ALPHA9-master:
    path: AllAPILoader-ALPHA9-master/
  AlwaysSpawn-final:
    path: AlwaysSpawn-final/
  Anvilrepair_plugin (1).Anvilrepair plugin.AnvilRepair_v1:
    path: Anvilrepair_plugin (1)/Anvilrepair plugin/AnvilRepair_v1/
  BanItem:
    path: BanItem/
  BlockCmdPE-patch-1:
    path: BlockCmdPE-patch-1/
  Broadcaster-master:
    path: Broadcaster-master/
  ClearLagg-patch-1:
    path: ClearLagg-patch-1/
  CombatTimer-patch-1:
    path: CombatTimer-patch-1/
  CustomAlerts-patch-1.CustomAlerts:
    path: CustomAlerts-patch-1/CustomAlerts/
  CustomAlerts-patch-1:
    path: CustomAlerts-patch-1/
  EconomyAPI:
    path: EconomyAPI/
  EconomyAirport:
    path: EconomyAirport/
  EconomyAuction:
    path: EconomyAuction/
  EconomyCasino:
    path: EconomyCasino/
  EconomyJob:
    path: EconomyJob/
  EconomyLand:
    path: EconomyLand/
  EconomyPShop:
    path: EconomyPShop/
  EconomyProperty:
    path: EconomyProperty/
  EconomySell:
    path: EconomySell/
  EconomyTax:
    path: EconomyTax/
  EconomyUsury:
    path: EconomyUsury/
  FactionsPro-patch-1:
    path: FactionsPro-patch-1/
  Functions-patch-2:
    path: Functions-patch-2/
  HungerDisabler-patch-1:
    path: HungerDisabler-patch-1/
  MobTags-master:
    path: MobTags-master/
  NameChanger-master:
    path: NameChanger-master/
  NoAdvertisingPE-patch-1:
    path: NoAdvertisingPE-patch-1/
  PureChat-patch-1:
    path: PureChat-patch-1/
  PurePerms-patch-1:
    path: PurePerms-patch-1/
  RestartMe-PocketMine-patch-1:
    path: RestartMe-PocketMine-patch-1/
  SafeFly-ZPlayzMCPE-pmmp:
    path: SafeFly-ZPlayzMCPE-pmmp/
  Sell-patch-5:
    path: Sell-patch-5/
  ServerGuide-master:
    path: ServerGuide-master/
  ServerRules-master:
    path: ServerRules-master/
  SimpleAuth-patch-2:
    path: SimpleAuth-patch-2/
  SimpleAuthHelper-patch-1:
    path: SimpleAuthHelper-patch-1/
  SimpleWarp-master:
    path: SimpleWarp-master/
  SuperBar:
    path: SuperBar/
  SuperVanish:
    path: SuperVanish/
  TimeCommander-patch-2.TimeCommander-patch-2:
    path: TimeCommander-patch-2/TimeCommander-patch-2/
  TimeCommander-patch-2:
    path: TimeCommander-patch-2/
  TimeRanks-patch-1:
    path: TimeRanks-patch-1/
  VMPE-Action-patch-2.VMPE-Action-patch-2:
    path: VMPE-Action-patch-2/VMPE-Action-patch-2/
  Wild:
    path: Wild/
  ZipPluginLoader-patch-1:
    path: ZipPluginLoader-patch-1/
...
